package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"math"
	"time"

	"github.com/jkzilla/egg-price-compare/graph/model"
)

// EggPrices is the resolver for the eggPrices field.
func (r *queryResolver) EggPrices(ctx context.Context, zipcode string) (*model.EggPriceComparison, error) {
	walmartPrice, err := r.Resolver.walmartAPI.GetEggPrice(zipcode)
	if err != nil {
		return nil, fmt.Errorf("failed to get Walmart price: %w", err)
	}

	walgreensPrice, err := r.Resolver.walgreensAPI.GetEggPrice(zipcode)
	if err != nil {
		return nil, fmt.Errorf("failed to get Walgreens price: %w", err)
	}

	cheapest := "Walmart"
	if walgreensPrice.FinalPrice < walmartPrice.FinalPrice {
		cheapest = "Walgreens"
	}

	priceDiff := math.Abs(walmartPrice.FinalPrice - walgreensPrice.FinalPrice)

	// Store in history
	historyEntry := model.PriceHistoryEntry{
		Date:           time.Now().Format("2006-01-02"),
		WalmartPrice:   walmartPrice.FinalPrice,
		WalgreensPrice: walgreensPrice.FinalPrice,
	}

	// Add to history if it's a new day
	if len(r.Resolver.priceHistory) == 0 || r.Resolver.priceHistory[len(r.Resolver.priceHistory)-1].Date != historyEntry.Date {
		r.Resolver.priceHistory = append(r.Resolver.priceHistory, historyEntry)
	}

	return &model.EggPriceComparison{
		Walmart:         walmartPrice,
		Walgreens:       walgreensPrice,
		Cheapest:        cheapest,
		PriceDifference: priceDiff,
		LastUpdated:     time.Now().Format(time.RFC3339),
	}, nil
}

// PriceHistory is the resolver for the priceHistory field.
func (r *queryResolver) PriceHistory(ctx context.Context, days *int) ([]*model.PriceHistoryEntry, error) {
	numDays := 7
	if days != nil {
		numDays = *days
	}

	// Return last N days
	start := len(r.Resolver.priceHistory) - numDays
	if start < 0 {
		start = 0
	}

	history := make([]*model.PriceHistoryEntry, 0)
	for i := start; i < len(r.Resolver.priceHistory); i++ {
		entry := r.Resolver.priceHistory[i]
		history = append(history, &entry)
	}

	return history, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	type Resolver struct {
	walmartAPI   *api.WalmartAPI
	walgreensAPI *api.WalgreensAPI
	priceHistory []model.PriceHistoryEntry
}
func NewResolver() *Resolver {
	return &Resolver{
		walmartAPI:   api.NewWalmartAPI(),
		walgreensAPI: api.NewWalgreensAPI(),
		priceHistory: []model.PriceHistoryEntry{},
	}
}
*/
