// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// The concrete GraphQL models are defined in models.go and
// referenced via the `models` mapping in gqlgen.yml.
// This file is intentionally minimal to avoid duplicate type
// definitions when generating code.

// Query is kept as a stub so gqlgen can compile its
// generated resolver signatures.
type Query struct{}
